### ISSUE TITLE
inconsistent definitions between search tool and 'all terms' page

### ISSUE THREAD

**Issue by sformel-usgs** [GenomicsStandardsConsortium/gensc.github.io#64]
**Describe the bug**
The GSC ['all terms' page](http://www.gensc.org/pages/standards/all-terms.html) lists different definitions, and other fields, when compared to the ['term search tool'](http://www.gensc.org/pages/standards/search-terms.html).  

**To Reproduce**
Compare MIXS:0000001 and MIXS:0000002 on each page.

**Expected behavior**
I would expect those pages to be pulling information from the same source and to see no difference between the information being served.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 112.0.1722.34 (Official build) (64-bit)

**Additional context**
It seems like the search tool is the one pulling the incorrect information, as the 'all terms' page aligns with the information in the [release](https://github.com/GenomicsStandardsConsortium/mixs/blob/main/mixs/excel/mixs_v6.xlsx).

**Comment by only1chunts** [comment]
Hi, many thanks for noticing. It is true that the search is still using the v5 terms whereas the all terms has been updated with the v6 where we made some adjustments to the definitions. I will attempt to get the search terms updated as soon as I can (I had some issues with the YAML formatting in the search terms document previously hence it didn't get done sooner).

**Comment by sformel-usgs** [comment]
Sounds good, I figured there was a simple explanation.  Thanks for responding so quickly!

**Comment by only1chunts** [comment]
Just to let you know, this feature will not be fixed in the gensc.org website, instead the feature will be replaced by the auto-generated documentation pages available [here](https://genomicsstandardsconsortium.github.io/mixs/term_list/) 
There is a big red notice on the [gensc.org/all-terms](https://www.gensc.org/pages/standards/all-terms.html) page to let users know the content is out of date. But as it is a very useful table to do quick filters and searches with I've left the page live for now.
